[palette]
background = "{{background}}"
foreground = "{{foreground}}"
primary = "{{color4}}"
secondary = "{{color2}}"
tertiary = "{{color5}}"
surface = "{{color0}}"
surface_bright = "{{color8}}"
outline = "{{color7}}"
error = "{{color1}}"
shadow = "{{color0}}"

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
style = "plain"
foreground = "p:foreground"
template = "\uF303"
type = "os"

[[blocks.segments]]
foreground = "p:primary"
style = "plain"
template = ' {{ "{{" }} .PWD {{ "}}" }} '
type = "path"
[blocks.segments.properties]
style = "agnoster"

[[blocks.segments]]
type = "rust"
foreground = "#FF4F00"
template = ' {{ "{{" }} .Full {{ "}}" }} '
style = "plain"

[[blocks.segments]]
type = "python"
foreground = "#100e23"
background = "#906cff"
template = ' {{ "{{" }} .Full {{ "}}" }} '
style = "plain"

# right prompt
[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
template = ' git: {{ "{{" }} .HEAD {{ "}}" }} '
foreground = "p:secondary"
style = "plain"
type = "git"

# time
[[blocks.segments]]
type = "time"
style = "plain"
foreground = "p:primary"
template = ' {{ "{{" }} .CurrentDate | date .Format {{ "}}" }} '
